# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: So You Want To Be Woke
description: >- # this means to ignore newlines until "baseurl:"
  The path to becoming woke is hard; this site’s meant to help you get there.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adicu
github_username:  woke
resource_images: ['https://source.unsplash.com/600x300/?african%20american',
  'https://source.unsplash.com/600x300/?landscape',
  'https://source.unsplash.com/600x300/?nature,water',
  'https://source.unsplash.com/600x300/?urban',
  'https://source.unsplash.com/600x300/?female',
  'https://source.unsplash.com/600x300/?team',
  'https://source.unsplash.com/600x300/?business',
  'https://source.unsplash.com/600x300/?city',
  'https://source.unsplash.com/600x300/?love',
  'https://source.unsplash.com/600x300/?architecture',
  'https://source.unsplash.com/600x300/?woman',
  'https://source.unsplash.com/600x300/?africa',
  'https://source.unsplash.com/600x300/?afro',
  'https://source.unsplash.com/600x300/?culture',
  'https://source.unsplash.com/600x300/?black%20skin',
  'https://source.unsplash.com/600x300/?african%20american,family',
  ]
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
